// ─── SEED: 87 Clientes da Criscontab & Madeira Contabilidade ───
const CLIENTES_SEED = [\n  {id:"1", nome:"ALINY PACHECO MADEIRA",                   cnpj:"13.886.410/0001-23", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"3", nome:"TOPOGRAFIA",                              cnpj:"09.035.469/0001-30", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"5", nome:"ASSOC. COMERCIAL AGROPECUÁRIAS POA",      cnpj:"13.373.835/0001-39", regime:"A definir", status:"Avaliar", obs:""},\n  {id:"15", nome:"SILVA MARTINS & MADEIRA LTDA",            cnpj:"02.773.274/0001-49", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"17", nome:"DEIVI TEIXEIRA HOMEM CLIMATIZAÇÃO",       cnpj:"19.679.735/0001-11", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"25", nome:"CRUZ E NUNES LTDA",                       cnpj:"29.081.138/0001-44", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"27", nome:"MARIA A MACHADO DA SILVA",                cnpj:"30.168.377/0001-15", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"30", nome:"Claudio Dias & Ferreira Ltda",            cnpj:"31.953.090/0001-69", regime:"—", status:"Inativo", obs:""},\n  {id:"31", nome:"TANIA MARIA DA SILVA PEREIRA",            cnpj:"31.099.512/0001-80", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"39", nome:"Jackson S. Alves Ltda",                   cnpj:"28.878.131/0001-95", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"40", nome:"GRUPO ESCOTEIRO LACADOR 358/RS",          cnpj:"32.267.461/0001-11", regime:"—", status:"Inativo", obs:""},\n  {id:"42", nome:"SRS MARMORES E GRANITOS LTDA",            cnpj:"38.657.850/0001-30", regime:"—", status:"Inativo", obs:""},\n  {id:"43", nome:"Andrea C. Lopes Ltda",                    cnpj:"40.344.162/0001-61", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"44", nome:"DSS OFICINA MECANICA LTDA",               cnpj:"41.594.175/0001-51", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"46", nome:"A S BRITO TOPOGRAFIA LTDA",               cnpj:"41.608.774/0001-87", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"50", nome:"JORNAL OPINIAO DE VIAMAO LTDA",           cnpj:"03.080.511/0001-59", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"54", nome:"V R POLICARPO & M L AQUINI VET",          cnpj:"43.971.841/0001-59", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"56", nome:"ERNESTO W. SIEGLE & FERNANDA S.",         cnpj:"19.191.198/0001-66", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"59", nome:"BERENICE DA ROSA SPADER PSICOLOGIA",      cnpj:"45.418.211/0001-87", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"61", nome:"CM SILVA & AGM SILVA LTDA",               cnpj:"19.534.212/0001-87", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"63", nome:"TATIANE C. NUNES LTDA",                   cnpj:"46.098.911/0001-02", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"64", nome:"J. S. DE MENEZES LTDA",                   cnpj:"27.880.916/0001-30", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"71", nome:"V. M. C. Rodrigues",                      cnpj:"45.887.448/0001-07", regime:"—", status:"Encerrada", obs:""},\n  {id:"72", nome:"M. V. D. DA SILVEIRA LTDA",               cnpj:"26.911.525/0001-72", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"73", nome:"P. H. M. Cabeleira",                      cnpj:"50.136.729/0001-68", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"74", nome:"P. J. Rolim Blum Ltda",                   cnpj:"50.163.065/0001-26", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"75", nome:"Pietrizze Ltda",                          cnpj:"50.595.713/0001-13", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"77", nome:"CAMILA OLIVEIRA DA COSTA LTDA",           cnpj:"50.738.200/0001-14", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"78", nome:"C. O. DA COSTA LTDA",                     cnpj:"51.473.994/0001-02", regime:"—", status:"Inativo", obs:""},\n  {id:"79", nome:"BUNKER 784 GASTROBAR LTDA",               cnpj:"44.679.580/0001-60", regime:"—", status:"Inativo", obs:""},\n  {id:"80", nome:"ADIR WEBBER DE MELO",                     cnpj:"18.742.086/0001-93", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"81", nome:"CRISTIANE SANTTANNA PEREIRA DA SILVA",    cnpj:"512.287.7952/09", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"82", nome:"GUILHERME DE OLIVEIRA NICOLAIT ME",       cnpj:"15.359.960/0001-10", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"84", nome:"SILVEIRA & SARAIVA REP. COMERCIAL",       cnpj:"30.646.826/0001-93", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"88", nome:"SPS SERV. CONTABILIDADE E ESTAMPARIA",    cnpj:"21.973.245/0001-75", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"89", nome:"KF TUR TRANSPORTES LTDA",                 cnpj:"06.256.034/0001-28", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"90", nome:"ALVAREZ COSTA DA SILVEIRA - ALVASERV",    cnpj:"22.075.504/0001-03", regime:"—", status:"Especial", obs:"Não é mais cliente — Não entregar"},\n  {id:"91", nome:"Partido Democratico Trabalhista",         cnpj:"91.744.912/0001-23", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"97", nome:"NOBRE RESIDENCIAL TERAPEUTICO LTDA",      cnpj:"41.266.568/0001-36", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"98", nome:"BONANZA FC",                              cnpj:"94.435.187/0001-08", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"99", nome:"RESIDENCIAL TERAPEUTICO LINEA LTDA",      cnpj:"30.719.029/0001-99", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"103", nome:"CLUBE DE MÃES COLMÉIA",                   cnpj:"90.091.059/0001-25", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"104", nome:"ANA DANIELA DA S. RODRIGUES",             cnpj:"17.205.225/0001-87", regime:"A definir", status:"Ativo", obs:""},\n  {id:"111", nome:"PATAS DO MUNDO VET ASSISTENCE LTDA",      cnpj:"43.511.808/0002-27", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"112", nome:"GERSON ROJAS DA SILVEIRA",                cnpj:"33.598.021/0001-00", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"113", nome:"GAUTEC TECNOLOGIA E SERVIÇOS LTDA 01",    cnpj:"10.821.321/0001-00", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"115", nome:"J.V. PAOLAZZI SALVI",                     cnpj:"50.512.267/0001-36", regime:"Lucro Real", status:"Ativo", obs:""},\n  {id:"116", nome:"ANDREA GUEDES MENDES",                    cnpj:"49.998.531/0001-04", regime:"—", status:"Inativo", obs:""},\n  {id:"119", nome:"LEDIANE SCARIOT SALLA",                   cnpj:"51.733.375/0001-00", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"120", nome:"VINICIUS ELSNER LANFREDI LTDA",           cnpj:"23.685.717/0001-10", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"121", nome:"CRISTIAN A MORALES YEPES LTDA",           cnpj:"52.658.733/0001-11", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"122", nome:"REIS E GONÇALVES REPRESENTAÇÕES",         cnpj:"36.834.126/0001-09", regime:"—", status:"Inativo", obs:""},\n  {id:"123", nome:"DAIANE PEREIRA DA SILVA",                 cnpj:"47.468.156/0001-65", regime:"MEI", status:"Ativo", obs:""},\n  {id:"124", nome:"RODRIGO DOS PASSOS",                      cnpj:"45.081.410/0001-42", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"125", nome:"C. O. DA COSTA & D. C. RODRIGUES",        cnpj:"50.714.685/0001-06", regime:"—", status:"Inativo", obs:""},\n  {id:"126", nome:"R. P. CHIMENES",                          cnpj:"36.492.896/0001-10", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"127", nome:"RENATA DOS REIS DOS SANTOS LTDA",         cnpj:"55.881.669/0001-21", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"128", nome:"CTG VAQUEANOS DA CULTURA",                cnpj:"29.275.771/0001-73", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"129", nome:"P. J. ROLIM BLUM LTDA 02",                cnpj:"50.163.065/0002-07", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"130", nome:"V. GONÇALVES DA SILVA LTDA",              cnpj:"56.659.939/0001-17", regime:"A definir", status:"Ativo", obs:""},\n  {id:"131", nome:"MARCOS ANTONIO DA ROSA DANTAS",           cnpj:"36.937.569/0001-25", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"132", nome:"TAIS DE ARAUJO PEREIRA",                  cnpj:"31.266.357/0001-40", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"133", nome:"G. S. GOULART LTDA",                      cnpj:"58.607.484/0001-11", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"134", nome:"RHISSAN KHALEK PACHECO",                  cnpj:"57.850.064/0001-07", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"135", nome:"E. AMARAL DA SILVA LTDA",                 cnpj:"56.970.630/0001-43", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"136", nome:"ALVAREZ K. JUNIOR & CAMILA O. LTDA",      cnpj:"58.652.716/0001-53", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"137", nome:"DIEGO VIEIRA ALVES LTDA",                 cnpj:"60.223.059/0001-70", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"138", nome:"PAMELA PAOLA OLIVEIRA ALVES LTDA",        cnpj:"53.507.129/0001-57", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"139", nome:"A. DA LUZ BRILHANTE LTDA",                cnpj:"60.945.272/0001-96", regime:"A definir", status:"Ativo", obs:""},\n  {id:"140", nome:"CARLOS ALEXANDRE ALMEIDA SEVERO",         cnpj:"38.164.377/0001-59", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"141", nome:"GAUTEC TECNOLOGIA E SERVIÇOS LTDA 02",    cnpj:"10.821.321/0002-91", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"142", nome:"GAUTEC TECNOLOGIA E SERVIÇOS LTDA 03",    cnpj:"10.821.321/0003-72", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"143", nome:"PARTIDO SOCIAL DEMOCRATICO - VIAMÃO",     cnpj:"23.974.235/0001-80", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"144", nome:"FORTE GASTRONOMIA LTDA",                  cnpj:"58.468.980/0001-31", regime:"Simples Nacional", status:"Ativo", obs:"Pendente: PDF dos Extratos Bancários"},\n  {id:"145", nome:"PRADO GASTRONOMIA LTDA",                  cnpj:"52.513.378/0001-92", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"146", nome:"IMOBILIARIA ROSPIDE LTDA ME",             cnpj:"92.490.804/0001-34", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"147", nome:"ROSPIDE SERV. E APOIO A EDIFÍCIOS",       cnpj:"04.352.348/0001-07", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"148", nome:"COND. EDIF. SETEMBRINA SOLAR CENTER",     cnpj:"45.201.315/0001-35", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"149", nome:"COND. QUERÊNCIA DAS ÁGUAS CLARAS",        cnpj:"08.491.952/0001-67", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"150", nome:"COND. RESIDENCIAL SANTORINI",             cnpj:"30.043.959/0001-75", regime:"Lucro Presumido", status:"Ativo", obs:""},\n  {id:"151", nome:"ANA PAULA MORAES DE ANDRADE LTDA",        cnpj:"61.707.179/0001-06", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"152", nome:"CRISTIANE LUTTJOHANN LTDA",               cnpj:"62.038.213/0001-60", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"153", nome:"ROGER DA SILVA MARTINS",                  cnpj:"62.137.845/0001-80", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"154", nome:"RESIDENCIAL TERAPÊUTICO NOBRE LTDA",      cnpj:"63.149.106/0001-71", regime:"Lucro Real", status:"Ativo", obs:""},\n  {id:"155", nome:"ANA PAULA PASCHOAL DA ROSA",              cnpj:"63.020.070/0001-21", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"156", nome:"PABLO FABIANO CHAVES DO NASCIMENTO",      cnpj:"63.102.868/0001-12", regime:"Simples Nacional", status:"Ativo", obs:""},\n  {id:"157", nome:"ANDREA CRISTIANE LOPES LTDA",             cnpj:"63.248.560/0001-80", regime:"Simples Nacional", status:"Ativo", obs:""},\n];

// ─── BANCOS FEBRABAN + BANRISUL ───
const BANCOS = [
  {cod:"001", nome:"Banco do Brasil"},
  {cod:"033", nome:"Santander"},
  {cod:"041", nome:"Banrisul"},
  {cod:"077", nome:"Banco Inter"},
  {cod:"104", nome:"Caixa Econômica Federal"},
  {cod:"208", nome:"BTG Pactual"},
  {cod:"237", nome:"Bradesco"},
  {cod:"260", nome:"Nubank"},
  {cod:"341", nome:"Itaú"},
  {cod:"422", nome:"Safra"},
  {cod:"748", nome:"Sicredi"},
  {cod:"756", nome:"Sicoob / Bancoob"},
];

// ─── CHECKLIST MENSAL — Modelo por categoria ───
const CHECKLIST_TEMPLATE = [
  { cat:"📊 ATIVO",      icon:"📊", items:[
    {key:"extrato_bb",    nome:"Extrato Bancário — Banco do Brasil",   regimes:["todos"], condicao:"banco_001",    obs:""},
    {key:"extrato_brad",  nome:"Extrato Bancário — Bradesco",          regimes:["todos"], condicao:"banco_237",    obs:""},
    {key:"extrato_cef",   nome:"Extrato Bancário — Caixa",             regimes:["todos"], condicao:"banco_104",    obs:""},
    {key:"extrato_itau",  nome:"Extrato Bancário — Itaú",              regimes:["todos"], condicao:"banco_341",    obs:""},
    {key:"extrato_sant",  nome:"Extrato Bancário — Santander",         regimes:["todos"], condicao:"banco_033",    obs:""},
    {key:"extrato_bans",  nome:"Extrato Bancário — Banrisul",          regimes:["todos"], condicao:"banco_041",    obs:""},
    {key:"extrato_sic",   nome:"Extrato Bancário — Sicredi",           regimes:["todos"], condicao:"banco_748",    obs:""},
    {key:"extrato_sicoob",nome:"Extrato Bancário — Sicoob",            regimes:["todos"], condicao:"banco_756",    obs:""},
    {key:"extrato_inter", nome:"Extrato Bancário — Inter",             regimes:["todos"], condicao:"banco_077",    obs:""},
    {key:"extrato_nu",    nome:"Extrato Bancário — Nubank",            regimes:["todos"], condicao:"banco_260",    obs:""},
    {key:"extrato_outro", nome:"Extrato Bancário — Outro banco",       regimes:["todos"], condicao:"banco_outro",  obs:""},
    {key:"aplicacoes",    nome:"Aplicações Financeiras",               regimes:["todos"], condicao:null,           obs:"Informe saldos e rendimentos"},
    {key:"caixa",         nome:"Controle de Caixa",                    regimes:["todos"], condicao:"tem_caixa",    obs:""},
    {key:"cr",            nome:"Contas a Receber — Relatório",         regimes:["todos"], condicao:null,           obs:""},
    {key:"estoque",       nome:"Inventário / Movimentação de Estoque", regimes:["todos"], condicao:"tem_estoque",  obs:""},
    {key:"imobilizado",   nome:"Imobilizado — Aquisições e Baixas",    regimes:["todos"], condicao:null,           obs:""},
  ]},
  { cat:"📊 PASSIVO",    icon:"📊", items:[
    {key:"cp",            nome:"Contas a Pagar — Relatório",           regimes:["todos"], condicao:null,           obs:""},
    {key:"emprestimos",   nome:"Empréstimos e Financiamentos",         regimes:["todos"], condicao:null,           obs:"Saldos e parcelas do mês"},
    {key:"parc_rfb",      nome:"Guia Parcelamento — Receita Federal",  regimes:["todos"], condicao:"parc_federal", obs:""},
    {key:"parc_estado",   nome:"Guia Parcelamento — Receita Estadual", regimes:["todos"], condicao:"parc_estadual",obs:""},
    {key:"parc_pref",     nome:"Guia Parcelamento — Prefeitura",       regimes:["todos"], condicao:"parc_pref",    obs:""},
    {key:"parc_pgfn",     nome:"Guia Parcelamento — Procuradoria PGFN",regimes:["todos"], condicao:"parc_pgfn",    obs:""},
    {key:"obrig_trab",    nome:"Obrigações Trabalhistas do Mês",       regimes:["todos"], condicao:"tem_folha",    obs:""},
  ]},
  { cat:"📊 PATRIMÔNIO", icon:"📊", items:[
    {key:"alt_contratual",nome:"Alterações Contratuais",               regimes:["todos"], condicao:null,           obs:"Enviar se houver alteração"},
    {key:"dist_lucros",   nome:"Distribuição de Lucros",               regimes:["Lucro Presumido","Lucro Real"], condicao:null, obs:""},
    {key:"integ_capital", nome:"Integralização de Capital",            regimes:["todos"], condicao:null,           obs:"Enviar se houver"},
  ]},
  { cat:"📊 RECEITAS",   icon:"📊", items:[
    {key:"nf_emitidas",   nome:"Notas Fiscais Emitidas (XML)",         regimes:["todos"], condicao:null,           obs:"Todas as NF-e e NFS-e do mês"},
    {key:"faturamento",   nome:"Relatório de Faturamento",             regimes:["todos"], condicao:null,           obs:""},
    {key:"serv_sem_nf",   nome:"Serviços Prestados sem Nota Fiscal",   regimes:["todos"], condicao:null,           obs:"⚠️ Ponto crítico — declarar todos"},
  ]},
  { cat:"📊 DESPESAS",   icon:"📊", items:[
    {key:"nf_entrada",    nome:"Notas Fiscais de Entrada (XML)",       regimes:["todos"], condicao:null,           obs:""},
    {key:"serv_tomados",  nome:"Serviços Tomados sem Nota",            regimes:["todos"], condicao:null,           obs:""},
    {key:"desp_op",       nome:"Despesas Operacionais — Comprovantes", regimes:["todos"], condicao:null,           obs:"Aluguéis, contas, etc."},
    {key:"cartao",        nome:"Fatura(s) do Cartão de Crédito",       regimes:["todos"], condicao:null,           obs:"PJ e PF se houver uso empresarial"},
  ]},
  { cat:"📊 FISCAL",     icon:"📊", items:[
    {key:"xml_entrada",   nome:"XMLs de Entrada (NF-e fornecedores)",  regimes:["todos"], condicao:"fiscal_integrado", obs:""},
    {key:"xml_saida",     nome:"XMLs de Saída (NF-e emitidas)",        regimes:["todos"], condicao:"fiscal_integrado", obs:""},
    {key:"apur_impostos", nome:"Apuração de Impostos do Mês",          regimes:["todos"], condicao:null,           obs:""},
    {key:"guias_pagas",   nome:"Guias de Impostos Pagas",              regimes:["todos"], condicao:null,           obs:"DAS, DARF, GPS, ISS etc."},
    {key:"pgdas",         nome:"PGDAS-D — Declaração Simples",         regimes:["Simples Nacional","MEI"], condicao:null, obs:""},
    {key:"dasn",          nome:"DASN — Declaração Anual MEI",          regimes:["MEI"], condicao:null,             obs:""},
  ]},
  { cat:"📊 FOLHA",      icon:"📊", items:[
    {key:"folha",         nome:"Folha de Pagamento do Mês",            regimes:["todos"], condicao:"tem_folha",    obs:""},
    {key:"prolabore",     nome:"Pró-labore dos Sócios",                regimes:["todos"], condicao:"tem_prolabore",obs:""},
    {key:"inss_fgts",     nome:"INSS e FGTS — Guias e Comprovantes",   regimes:["todos"], condicao:"tem_folha",    obs:""},
    {key:"rescisoes",     nome:"Rescisões / Admissões do Mês",         regimes:["todos"], condicao:"tem_folha",    obs:"Se houver movimentação"},
  ]},
];

// ─── CHECKLIST ONBOARDING C-006 ───
const C006_TEMPLATE = [
  { section:"Dados do Sócio", items:[
    {cod:"1001", nome:"Certificado Digital (PJ)", obs:"Obrigatório"},
    {cod:"1002", nome:"CNH e/ou Documento com Foto", obs:"Obrigatório"},
    {cod:"1003", nome:"Certidão de Casamento", obs:"Opcional"},
    {cod:"1006", nome:"Comprovante de Endereço", obs:"Opcional"},
    {cod:"—",    nome:"Acesso GOV do Sócio (usuário e senha)", obs:"Salvar em TXT seguro no servidor"},
    {cod:"—",    nome:"Acesso Portal da Prefeitura", obs:""},
  ]},
  { section:"IRPF via App GOV do Sócio", items:[
    {cod:"1201", nome:"IRPF 2024 (ano-base 2023) — Recibo", obs:""},
    {cod:"1202", nome:"IRPF 2024 (ano-base 2023) — Declaração", obs:""},
    {cod:"1203", nome:"IRPF 2024 (ano-base 2023) — Guia", obs:""},
    {cod:"1204", nome:"Relatório Gerencial de Conferência", obs:"Gerado pelo escritório — não solicitar ao cliente"},
  ]},
  { section:"Documentos do CNPJ (solicitar ao cliente)", items:[
    {cod:"1301", nome:"Contrato de MEI", obs:"Se MEI"},
    {cod:"1302", nome:"Contrato ME", obs:"Se ME"},
    {cod:"1303", nome:"Contrato LTDA", obs:"Se LTDA"},
    {cod:"1304", nome:"Alvará", obs:"Obrigatório"},
    {cod:"1305", nome:"Comunicado de Desenquadramento do MEI", obs:"Se houver"},
    {cod:"1310", nome:"Laudo PGR", obs:"Solicitar"},
    {cod:"1311", nome:"Comprovante de Inscrição de IPTU", obs:"Opcional — casos específicos"},
    {cod:"1313", nome:"FCN", obs:"Solicitar"},
    {cod:"1314", nome:"Viabilidade", obs:"Solicitar"},
    {cod:"1315", nome:"DBE", obs:"Solicitar"},
    {cod:"1317", nome:"SST — LTCAT", obs:"Solicitar"},
    {cod:"1318", nome:"SST — PMSO", obs:"Solicitar"},
    {cod:"1319", nome:"SST — Modelo OS", obs:"Opcional"},
    {cod:"1320", nome:"SST — Controle de EPI", obs:"Opcional"},
  ]},
  { section:"Documentos que o Escritório Consulta Online", items:[
    {cod:"1306", nome:"Inscrição Municipal", obs:"Via site da Prefeitura pelo CNPJ"},
    {cod:"1307", nome:"Situação Fiscal", obs:"Via e-CAC"},
    {cod:"1308", nome:"Comprovante de Opção de Regime", obs:"Via e-CAC"},
    {cod:"1309", nome:"Código de Acesso Simples Nacional", obs:"Solicitar ou gerar novo"},
    {cod:"1312", nome:"Inscrição Estadual", obs:"Via site do Governo pelo CNPJ"},
    {cod:"1316", nome:"Recibo DTE (Domicílio Eletrônico)", obs:"Via e-CAC"},
    {cod:"1321", nome:"QSA — Quadro dos Sócios", obs:"Via e-CAC"},
    {cod:"1322", nome:"Optante pelo Simples Nacional", obs:"Verificar"},
    {cod:"1398", nome:"Parecer", obs:"Elaborado pelo escritório"},
    {cod:"1399", nome:"Cartão CNPJ", obs:"Via site de consulta de CNPJ"},
  ]},
  { section:"Parcelamentos em Andamento", items:[
    {cod:"3502", nome:"Documento Parcelamento MEI", obs:""},
    {cod:"3503", nome:"Documento Parcelamento Simples Nacional — RFB", obs:""},
    {cod:"3504", nome:"Documento Parcelamento PJ Geral — RFB", obs:""},
    {cod:"3505", nome:"Documento Parcelamento Procuradoria — DU", obs:""},
    {cod:"3506", nome:"Documento Parcelamento Estado", obs:""},
    {cod:"3507", nome:"Documento Parcelamento Município", obs:""},
  ]},
  { section:"Parametrizações do Sistema", items:[
    {cod:"3601", nome:"ÚNICO — Cadastrar Empresa", obs:""},
    {cod:"3602", nome:"ÚNICO — Cadastrar Sócios", obs:""},
    {cod:"3603", nome:"ÚNICO — Marcar Tecnologias Web", obs:""},
    {cod:"3604", nome:"TecWeb — Configurar Login e Senha", obs:""},
    {cod:"3605", nome:"TecWeb — Controle de Senha: Configurar Senha GOV", obs:""},
    {cod:"3606", nome:"TecWeb — Senhas recebidas do contador anterior", obs:""},
    {cod:"3612", nome:"e-CAC — Vincular Procuração (Cert. PJ)", obs:""},
    {cod:"3613", nome:"SAT/SEFAZ — Vincular Procuração", obs:""},
    {cod:"3614", nome:"ÚNICO — Configurar Certificado Procuração", obs:""},
    {cod:"3615", nome:"PUSH — Configuração do ISS Legal", obs:""},
  ]},
];
