// ─── CLIENTES_SEED está definido em seed.js (fonte única de dados) ───

// ─── BANCOS FEBRABAN + BANRISUL ───
const BANCOS = [
  {cod:"001", nome:"Banco do Brasil"},
  {cod:"033", nome:"Santander"},
  {cod:"041", nome:"Banrisul"},
  {cod:"077", nome:"Banco Inter"},
  {cod:"104", nome:"Caixa Econômica Federal"},
  {cod:"208", nome:"BTG Pactual"},
  {cod:"237", nome:"Bradesco"},
  {cod:"260", nome:"Nubank"},
  {cod:"341", nome:"Itaú"},
  {cod:"422", nome:"Safra"},
  {cod:"748", nome:"Sicredi"},
  {cod:"756", nome:"Sicoob / Bancoob"},
];

// ─── CHECKLIST MENSAL — Modelo por categoria ───
const CHECKLIST_TEMPLATE = [
  { cat:"📊 ATIVO",      icon:"📊", items:[
    {key:"extrato_bb",    nome:"Extrato Bancário — Banco do Brasil",   regimes:["todos"], condicao:"banco_001",    obs:""},
    {key:"extrato_brad",  nome:"Extrato Bancário — Bradesco",          regimes:["todos"], condicao:"banco_237",    obs:""},
    {key:"extrato_cef",   nome:"Extrato Bancário — Caixa",             regimes:["todos"], condicao:"banco_104",    obs:""},
    {key:"extrato_itau",  nome:"Extrato Bancário — Itaú",              regimes:["todos"], condicao:"banco_341",    obs:""},
    {key:"extrato_sant",  nome:"Extrato Bancário — Santander",         regimes:["todos"], condicao:"banco_033",    obs:""},
    {key:"extrato_bans",  nome:"Extrato Bancário — Banrisul",          regimes:["todos"], condicao:"banco_041",    obs:""},
    {key:"extrato_sic",   nome:"Extrato Bancário — Sicredi",           regimes:["todos"], condicao:"banco_748",    obs:""},
    {key:"extrato_sicoob",nome:"Extrato Bancário — Sicoob",            regimes:["todos"], condicao:"banco_756",    obs:""},
    {key:"extrato_inter", nome:"Extrato Bancário — Inter",             regimes:["todos"], condicao:"banco_077",    obs:""},
    {key:"extrato_nu",    nome:"Extrato Bancário — Nubank",            regimes:["todos"], condicao:"banco_260",    obs:""},
    {key:"extrato_outro", nome:"Extrato Bancário — Outro banco",       regimes:["todos"], condicao:"banco_outro",  obs:""},
    {key:"aplicacoes",    nome:"Aplicações Financeiras",               regimes:["todos"], condicao:null,           obs:"Informe saldos e rendimentos"},
    {key:"caixa",         nome:"Controle de Caixa",                    regimes:["todos"], condicao:"tem_caixa",    obs:""},
    {key:"cr",            nome:"Contas a Receber — Relatório",         regimes:["todos"], condicao:null,           obs:""},
    {key:"estoque",       nome:"Inventário / Movimentação de Estoque", regimes:["todos"], condicao:"tem_estoque",  obs:""},
    {key:"imobilizado",   nome:"Imobilizado — Aquisições e Baixas",    regimes:["todos"], condicao:null,           obs:""},
  ]},
  { cat:"📊 PASSIVO",    icon:"📊", items:[
    {key:"cp",            nome:"Contas a Pagar — Relatório",           regimes:["todos"], condicao:null,           obs:""},
    {key:"emprestimos",   nome:"Empréstimos e Financiamentos",         regimes:["todos"], condicao:null,           obs:"Saldos e parcelas do mês"},
    {key:"parc_rfb",      nome:"Guia Parcelamento — Receita Federal",  regimes:["todos"], condicao:"parc_federal", obs:""},
    {key:"parc_estado",   nome:"Guia Parcelamento — Receita Estadual", regimes:["todos"], condicao:"parc_estadual",obs:""},
    {key:"parc_pref",     nome:"Guia Parcelamento — Prefeitura",       regimes:["todos"], condicao:"parc_pref",    obs:""},
    {key:"parc_pgfn",     nome:"Guia Parcelamento — Procuradoria PGFN",regimes:["todos"], condicao:"parc_pgfn",    obs:""},
    {key:"obrig_trab",    nome:"Obrigações Trabalhistas do Mês",       regimes:["todos"], condicao:"tem_folha",    obs:""},
  ]},
  { cat:"📊 PATRIMÔNIO", icon:"📊", items:[
    {key:"alt_contratual",nome:"Alterações Contratuais",               regimes:["todos"], condicao:null,           obs:"Enviar se houver alteração"},
    {key:"dist_lucros",   nome:"Distribuição de Lucros",               regimes:["Lucro Presumido","Lucro Real"], condicao:null, obs:""},
    {key:"integ_capital", nome:"Integralização de Capital",            regimes:["todos"], condicao:null,           obs:"Enviar se houver"},
  ]},
  { cat:"📊 RECEITAS",   icon:"📊", items:[
    {key:"nf_emitidas",   nome:"Notas Fiscais Emitidas (XML)",         regimes:["todos"], condicao:null,           obs:"Todas as NF-e e NFS-e do mês"},
    {key:"faturamento",   nome:"Relatório de Faturamento",             regimes:["todos"], condicao:null,           obs:""},
    {key:"serv_sem_nf",   nome:"Serviços Prestados sem Nota Fiscal",   regimes:["todos"], condicao:null,           obs:"⚠️ Ponto crítico — declarar todos"},
  ]},
  { cat:"📊 DESPESAS",   icon:"📊", items:[
    {key:"nf_entrada",    nome:"Notas Fiscais de Entrada (XML)",       regimes:["todos"], condicao:null,           obs:""},
    {key:"serv_tomados",  nome:"Serviços Tomados sem Nota",            regimes:["todos"], condicao:null,           obs:""},
    {key:"desp_op",       nome:"Despesas Operacionais — Comprovantes", regimes:["todos"], condicao:null,           obs:"Aluguéis, contas, etc."},
    {key:"cartao",        nome:"Fatura(s) do Cartão de Crédito",       regimes:["todos"], condicao:null,           obs:"PJ e PF se houver uso empresarial"},
  ]},
  { cat:"📊 FISCAL",     icon:"📊", items:[
    {key:"xml_entrada",   nome:"XMLs de Entrada (NF-e fornecedores)",  regimes:["todos"], condicao:"fiscal_integrado", obs:""},
    {key:"xml_saida",     nome:"XMLs de Saída (NF-e emitidas)",        regimes:["todos"], condicao:"fiscal_integrado", obs:""},
    {key:"apur_impostos", nome:"Apuração de Impostos do Mês",          regimes:["todos"], condicao:null,           obs:""},
    {key:"guias_pagas",   nome:"Guias de Impostos Pagas",              regimes:["todos"], condicao:null,           obs:"DAS, DARF, GPS, ISS etc."},
    {key:"pgdas",         nome:"PGDAS-D — Declaração Simples",         regimes:["Simples Nacional","MEI"], condicao:null, obs:""},
    {key:"dasn",          nome:"DASN — Declaração Anual MEI",          regimes:["MEI"], condicao:null,             obs:""},
  ]},
  { cat:"📊 FOLHA",      icon:"📊", items:[
    {key:"folha",         nome:"Folha de Pagamento do Mês",            regimes:["todos"], condicao:"tem_folha",    obs:""},
    {key:"prolabore",     nome:"Pró-labore dos Sócios",                regimes:["todos"], condicao:"tem_prolabore",obs:""},
    {key:"inss_fgts",     nome:"INSS e FGTS — Guias e Comprovantes",   regimes:["todos"], condicao:"tem_folha",    obs:""},
    {key:"rescisoes",     nome:"Rescisões / Admissões do Mês",         regimes:["todos"], condicao:"tem_folha",    obs:"Se houver movimentação"},
  ]},
];

// ─── CHECKLIST ONBOARDING C-006 ───
const C006_TEMPLATE = [
  { section:"Dados do Sócio", items:[
    {cod:"1001", nome:"Certificado Digital (PJ)", obs:"Obrigatório"},
    {cod:"1002", nome:"CNH e/ou Documento com Foto", obs:"Obrigatório"},
    {cod:"1003", nome:"Certidão de Casamento", obs:"Opcional"},
    {cod:"1006", nome:"Comprovante de Endereço", obs:"Opcional"},
    {cod:"—",    nome:"Acesso GOV do Sócio (usuário e senha)", obs:"Salvar em TXT seguro no servidor"},
    {cod:"—",    nome:"Acesso Portal da Prefeitura", obs:""},
  ]},
  { section:"IRPF via App GOV do Sócio", items:[
    {cod:"1201", nome:"IRPF 2024 (ano-base 2023) — Recibo", obs:""},
    {cod:"1202", nome:"IRPF 2024 (ano-base 2023) — Declaração", obs:""},
    {cod:"1203", nome:"IRPF 2024 (ano-base 2023) — Guia", obs:""},
    {cod:"1204", nome:"Relatório Gerencial de Conferência", obs:"Gerado pelo escritório — não solicitar ao cliente"},
  ]},
  { section:"Documentos do CNPJ (solicitar ao cliente)", items:[
    {cod:"1301", nome:"Contrato de MEI", obs:"Se MEI"},
    {cod:"1302", nome:"Contrato ME", obs:"Se ME"},
    {cod:"1303", nome:"Contrato LTDA", obs:"Se LTDA"},
    {cod:"1304", nome:"Alvará", obs:"Obrigatório"},
    {cod:"1305", nome:"Comunicado de Desenquadramento do MEI", obs:"Se houver"},
    {cod:"1310", nome:"Laudo PGR", obs:"Solicitar"},
    {cod:"1311", nome:"Comprovante de Inscrição de IPTU", obs:"Opcional — casos específicos"},
    {cod:"1313", nome:"FCN", obs:"Solicitar"},
    {cod:"1314", nome:"Viabilidade", obs:"Solicitar"},
    {cod:"1315", nome:"DBE", obs:"Solicitar"},
    {cod:"1317", nome:"SST — LTCAT", obs:"Solicitar"},
    {cod:"1318", nome:"SST — PMSO", obs:"Solicitar"},
    {cod:"1319", nome:"SST — Modelo OS", obs:"Opcional"},
    {cod:"1320", nome:"SST — Controle de EPI", obs:"Opcional"},
  ]},
  { section:"Documentos que o Escritório Consulta Online", items:[
    {cod:"1306", nome:"Inscrição Municipal", obs:"Via site da Prefeitura pelo CNPJ"},
    {cod:"1307", nome:"Situação Fiscal", obs:"Via e-CAC"},
    {cod:"1308", nome:"Comprovante de Opção de Regime", obs:"Via e-CAC"},
    {cod:"1309", nome:"Código de Acesso Simples Nacional", obs:"Solicitar ou gerar novo"},
    {cod:"1312", nome:"Inscrição Estadual", obs:"Via site do Governo pelo CNPJ"},
    {cod:"1316", nome:"Recibo DTE (Domicílio Eletrônico)", obs:"Via e-CAC"},
    {cod:"1321", nome:"QSA — Quadro dos Sócios", obs:"Via e-CAC"},
    {cod:"1322", nome:"Optante pelo Simples Nacional", obs:"Verificar"},
    {cod:"1398", nome:"Parecer", obs:"Elaborado pelo escritório"},
    {cod:"1399", nome:"Cartão CNPJ", obs:"Via site de consulta de CNPJ"},
  ]},

  { section:"Parametrizações do Sistema", items:[
    {cod:"3601", nome:"ÚNICO — Cadastrar Empresa", obs:""},
    {cod:"3602", nome:"ÚNICO — Cadastrar Sócios", obs:""},
    {cod:"3603", nome:"ÚNICO — Marcar Tecnologias Web", obs:""},
    {cod:"3604", nome:"TecWeb — Configurar Login e Senha", obs:""},
    {cod:"3605", nome:"TecWeb — Controle de Senha: Configurar Senha GOV", obs:""},
    {cod:"3606", nome:"TecWeb — Senhas recebidas do contador anterior", obs:""},
    {cod:"3612", nome:"e-CAC — Vincular Procuração (Cert. PJ)", obs:""},
    {cod:"3613", nome:"SAT/SEFAZ — Vincular Procuração", obs:""},
    {cod:"3614", nome:"ÚNICO — Configurar Certificado Procuração", obs:""},
    {cod:"3615", nome:"PUSH — Configuração do ISS Legal", obs:""},
  ]},
];
